flags: {}
extra-package-dbs: []

nix:
  enable: true
  packages:
    - libcxx
    - icu

packages:
- ./rasa
- ./rasa-ext-cmd
- ./rasa-ext-cursors
- ./rasa-ext-files
- ./rasa-ext-logger
- ./rasa-ext-slate
- ./rasa-ext-views
- ./rasa-ext-vim
- ./rasa-example-config
- ./text-lens
- ../eve

extra-deps:
# - eve-0.1.0
- vty-5.14
- recursion-schemes-5.0.1

# Uncomment the following if you'd like to use a locally installed version
# of icu4c INSTEAD of relying on nix.
#
# extra-lib-dirs:
# - /usr/local/opt/icu4c/lib
# extra-include-dirs:
# - /usr/local/opt/icu4c/include

resolver: lts-7.11
pvp-bounds: both
