flags: {}
extra-package-dbs: []
packages:
- ./rasa
- ./rasa-ext-cmd
- ./rasa-ext-cursors
- ./rasa-ext-files
- ./rasa-ext-logger
- ./rasa-ext-slate
- ./rasa-ext-status-bar
- ./rasa-ext-style
- ./rasa-ext-viewports
- ./rasa-ext-vim
- ./rasa-example-config
- ./text-lens

extra-deps:
- vty-5.14

extra-lib-dirs:
- /usr/local/opt/icu4c/lib 
extra-include-dirs:
- /usr/local/opt/icu4c/include

resolver: lts-7.11
pvp-bounds: both
