flags: {}
extra-package-dbs: []
packages:
- ./rasa
- ./rasa-core
- ./rasa-ext
- ./rasa-ext-cursors
- ./rasa-ext-files
- ./rasa-ext-logger
- ./rasa-ext-status-bar
- ./rasa-ext-style
- ./rasa-ext-vim
- ./rasa-renderer-slate
- ./text-lens
- ./rasa-example-config

extra-deps:
- vty-5.14

extra-lib-dirs:
- /usr/local/opt/icu4c/lib 
extra-include-dirs:
- /usr/local/opt/icu4c/include

resolver: lts-7.11
