flags: {}
extra-package-dbs: []
packages:
- ./rasa
- ./rasa-adapter-vty
- ./rasa-core
- ./rasa-ext
- ./rasa-ext-cursors
- ./rasa-ext-files
- ./rasa-ext-logger
- ./rasa-ext-status-bar
- ./rasa-ext-style
- ./rasa-ext-vim
- ./text-lens
- ./user-config
extra-deps:
- vty-5.14
resolver: lts-7.11
